### ISSUE TITLE
报错：No module named 'ppdet.utils.export_utils'

### ISSUE THREAD

**Issue by Alex28132** [enpeizhao/CVprojects#13]
在static文件夹下想export模型，报错：Traceback (most recent call last):
File "tools/export_model.py", line 53, in 
raise e
File "tools/export_model.py", line 40, in 
from ppdet.utils.export_utils import save_infer_model, dump_infer_config
ModuleNotFoundError: No module named 'ppdet.utils.export_utils'
不知道咋解决，请求帮助
输入命令是这个：python tools/export_model.py -c ./configs/rcnn_enhance/generic/cascade_rcnn_dcn_r101_vd_fpn_gen_server_side.yml --output_dir=./inference_model -o weights=./weights/cascade_rcnn_dcn_r101_vd_fpn_gen_server_side.pdparams  
不知道能否分享一份生成的infer_cfg.yml, model.pdiparams, model.pdiparams.info, model.pdmodel吗

**Comment by Alex28132** [comment]
解决了，删掉了虚拟环境，创建环境并重新配置环境就行了
