### ISSUE TITLE
关于人脸考勤机

### ISSUE THREAD

**Issue by llechee** [enpeizhao/CVprojects#33]
识别时出现错误

Traceback (most recent call last):
  File "demo_full.py", line 479, in <module>
    faceRecognize(detector=args.detector,threshold=args.threshold, write_video = args.record,resize_w=args.w,resize_h=args.h)
  File "demo_full.py", line 422, in faceRecognize
    frame = updateRightInfo(frame,face_info_list,face_img_list)
  File "demo_full.py", line 200, in updateRightInfo
    frame[(left_y+offset_y_value):(left_y+resize_w+ offset_y_value), -(left_x+resize_w):-left_x] = face_img
ValueError: could not broadcast input array from shape (80,80,3) into shape (0,80,3)

刷新时大小不一致，请问怎么解决呢

**Comment by enpeizhao** [comment]
应该是截图时人脸靠近边缘了，所以越界大小不一，要加一个判断
