### ISSUE TITLE
结印代码希望在 mac 下运行

### ISSUE THREAD

**Issue by fanxy1** [enpeizhao/CVprojects#5]

**Comment by enpeizhao** [comment]
MAC没有CUDA环境，暂时不好移植

**Comment by lulurelax** [comment]
MAC已经跑起来了，但是不建议。CPU只能跑1fps

**Comment by fanxy1** [comment]
> MAC已经跑起来了，但是不建议。CPU只能跑1fps

怎么跑呢，求操作步骤

**Comment by enpeizhao** [comment]
@bill1997603 可以看一下另一个分支， @lewisgit 贡献了macOS的运行方式，但受硬件限制帧率比较低

**Comment by fanxy1** [comment]
> @bill1997603 可以看一下另一个分支， @lewisgit 贡献了macOS的运行方式，但受硬件限制帧率比较低

👌

**Comment by fanxy1** [comment]
python3 codes/8.结印识别/main/train.py

Traceback (most recent call last):
  File "/Users/fxy/PycharmProjects/CVprojects/codes/8.结印识别/main/train.py", line 84, in <module>
    main()
  File "/Users/fxy/PycharmProjects/CVprojects/codes/8.结印识别/main/train.py", line 34, in main
    args = parse_args()
  File "/Users/fxy/PycharmProjects/CVprojects/codes/8.结印识别/main/train.py", line 21, in parse_args
    assert 0, "Please set propoer gpu ids"
AssertionError: Please set propoer gpu ids

这个怎么指定 gpu ids 呢？
@lewisgit
